### PR TITLE
Address lint warnings

### PR DESCRIPTION
**Pull request by PaulioRandall**
**What does this change?**

Addresses lint warnings, mostly removing unused imports and variables. Also allows `any` as TS is not used for validation.

**Why?**

It's becoming increasingly difficult to see the lint issues relating to the components currently being worked on due to the lint warning clutter in terminal.

**How?**

By addressing the warnings.

### CODE REVIEW

**Comment by jamesscottbrown** [comment]
This is mostly good, but I'd leave the `charts` package for now as it is being significantly re-written in the `next` branch.

**Comment by jamesscottbrown** [comment]
I'd also leave the `tables` package - I need to make various changes to it, and will address linter warnings for it at the same time.

**Comment by ChrisKnightLDN** [comment]
Should we address the no-explicit-any warnings rather than silence them?

**Comment by ChrisKnightLDN** [comment]
Related: #183 - this PR will not solve the issue of incorrect types

**Pull request merged**
